# Generated by Django 5.0 on 2024-01-11 19:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorVariant",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_up", models.DateTimeField(auto_now=True)),
                ("updated_up", models.DateTimeField(auto_now_add=True)),
                ("color_name", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SizeVariant",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_up", models.DateTimeField(auto_now=True)),
                ("updated_up", models.DateTimeField(auto_now_add=True)),
                ("size_name", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="product",
            old_name="products_name",
            new_name="product_name",
        ),
        migrations.AlterField(
            model_name="category",
            name="category_image",
            field=models.ImageField(upload_to="catgories"),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_up",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_up",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_up",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_up",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="created_up",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="updated_up",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="product",
            name="color_variant",
            field=models.ManyToManyField(blank=True, to="products.colorvariant"),
        ),
        migrations.AddField(
            model_name="product",
            name="size_variant",
            field=models.ManyToManyField(blank=True, to="products.sizevariant"),
        ),
    ]
