# Generated by Django 5.0 on 2024-01-12 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_cartitems_color_variant_and_more"),
        ("products", "0005_alter_productimage_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color_variant",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size_variant",
        ),
        migrations.DeleteModel(
            name="ColorVariant",
        ),
        migrations.DeleteModel(
            name="SizeVariant",
        ),
    ]
