# Generated by Django 5.0 on 2024-01-12 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_cart_cartitems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitems",
            name="color_variant",
        ),
        migrations.RemoveField(
            model_name="cartitems",
            name="size_variant",
        ),
    ]
